name: "Docker"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight
    
permissions:
  contents: "write"
  packages: "write"
  
env:
  CONTAINER_REGISTRY: ghcr.io
  CONTAINER_NAME: weasyprint/weasyprint
  
jobs:
  release:
    runs-on: "ubuntu-latest"
    
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v3"
        
      - name: "Reactivate Repository"
        uses: "custom-workflows/reactivate@latest"
        with: 
          commit_message: "github-actions: Reactivate repository"
          committer_username: "GitHub Actions [Bot]"
          committer_email: "github-actions[bot]@users.noreply.github.com"
          days_elapsed: 50
          
      - name: "Fetch Latest Version from PyPI.org"
        id: "pypi"
        shell: "bash"
        run: |
          version=$(curl -sSL https://pypi.org/pypi/weasyprint/json | jq '.info.version')

          echo "version=$version" >> "$GITHUB_OUTPUT"
            
      - name: "Login [ghcr.io]"
        uses: "docker/login-action@v2.1.0"
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: "Extract MetaData (Tags, Labels)"
        id: "metadata"
        uses: "docker/metadata-action@v4.3.0"
        with:
          images: ${{ env.CONTAINER_REGISTRY }}/${{ env.CONTAINER_NAME }}
          tags: |
            ${{ steps.pypi.outputs.version }}
            latest
          labels: |
            org.opencontainers.image.title=WeasyPrint
            org.opencontainers.image.version=${{ steps.pypi.outputs.version }}
          
      - name: "Build & Push"
        uses: "docker/build-push-action@v4.0.0"
        with:
          context: "."
          push: "true"
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}